=== Aya253resja/XML-Tasks/valid lab1.dtd
<?xml version="1.0" encoding="UTF-8"?>

  <!ELEMENT libarary (book+)>
  <!ATTLIST libaray 
    location CDATA #REQUIRED
    description CDATA #IMPLIED
    librarian (aya|esraa) #REQUIRED >
    
  <!ELEMENT book (perface,parts*)>
  <!ATTLIST book
    ISBN CDATA #REQUIRED 
    title CDATA #REQUIRED
    author CDATA #REQUIRED>
    
    
  <!ELEMENT perface (#PCDATA) >
    
  <!ELEMENT parts (chapters*)>
  <!ATTLIST parts
    title CDATA #REQUIRED>
  

  <!ELEMENT chapters (section,summary)>
  <!ENTITY title "This Is Constant Title" >

  <!ATTLIST chapters
    title CDATA #REQUIRED>
    
  <!ELEMENT summary (#PCDATA)>

  <!ELEMENT section (content)>

  <!ELEMENT content (p*)>

  <!ELEMENT p (#PCDATA) >

  <!ENTITY summary "This is an external summary">

=== Aya253resja/XML-Tasks/lab1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libarary SYSTEM "C:\Users\Aya Rashdan\Desktop\XML tasks\valid lab1.dtd">
<libarary location="" description="" libriran="aya">
	<book ISBN="D1" title="" auther="">
		<perface/>
		<parts title="">
			<chapters title="">
				<summary>&summary;</summary>
				<section>
					<content>
						<p><![CDATA[]]></p>
					</content>
				</section>
			</chapters>
		</parts>
	</book>
</libarary>
